name: Deploy - Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ secrets.GHCR_USER }} --password-stdin

      - name: Lowercase repo name
        run: echo "REPO_LOWER=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build image
        run: |
          docker build -t ghcr.io/${{ env.REPO_LOWER }}/myapp:latest .

      - name: Push image
        run: docker push ghcr.io/${{ env.REPO_LOWER }}/myapp:latest
